name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container:
      image: node:12.15.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install npm modules
        run: npm ci
      - name: Build production
        run: npm run build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIBRARIAN_SANDBOX }}'
          projectId: librarian-sandbox
